name: React

on:
  push:
    # Запуск рабочего процесса при коммите в ветку "master"
    branches: [ "master" ]
  pull_request:
    # Запуск рабочего процесса при создании pull request в ветку "master"
    branches: [ "master" ]

jobs:
  build:
    # Задачи будут выполняться на последней версии Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Используем действие для проверки кода из репозитория
        uses: actions/checkout@v3

      - name: Set up Node.js
        # Настраиваем Node.js
        uses: actions/setup-node@v3
        with:
          # Указываем версию Node.js, которую нужно использовать
          node-version: '20.16.0'

      - name: Install dependencies
        # Устанавливаем зависимости проекта
        run: npm install

      - name: Run type-check
        # Запускаем проверку типов
        run: npm run type-check

      - name: Run lint
        # Запускаем линтер для проверки кода
        run: npm run lint

      - name: Run format
        # Запускаем форматирование кода
        run: npm run format

      - name: Run tests
        # Запускаем тесты
        # Запускаем тесты
        run: npm test
